sonar.projectKey=thelagomorpha_neurobuddy-game
sonar.organization=thelagomorpha

# Only analyze production scripts
sonar.sources=Assets/Scripts/
sonar.sourceEncoding=UTF-8

# Exclude non-code files
sonar.exclusions=**/*.meta,**/*.asset,**/*.prefab,**/*.unity,**/*.mat,**/*.shader
